// <auto-generated />
using ForzaColourSearch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ForzaColourSearch.Migrations
{
    [DbContext(typeof(ForzaColourSearchContext))]
    [Migration("20211219192524_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ForzaColourSearch.Models.Vehicle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrightnessX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrightnessY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COLOURX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COLOURY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColourName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaturationX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaturationY")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
